// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "MaterialComponents",
    platforms: [
        .iOS(.v9) // eski sürüm olduğu için 9’a çektim
    ],
    products: [
        .library(name: "MaterialComponentsActivityIndicator", targets: ["MaterialComponentsActivityIndicator"]),
        .library(name: "MaterialComponentsAnimationTiming", targets: ["MaterialComponentsAnimationTiming"]),
        .library(name: "MaterialComponentsAppBar", targets: ["MaterialComponentsAppBar"]),
        .library(name: "MaterialComponentsBottomAppBar", targets: ["MaterialComponentsBottomAppBar"]),
        .library(name: "MaterialComponentsBottomSheet", targets: ["MaterialComponentsBottomSheet"]),
        .library(name: "MaterialComponentsButtonBar", targets: ["MaterialComponentsButtonBar"]),
        .library(name: "MaterialComponentsButtons", targets: ["MaterialComponentsButtons"]),
        .library(name: "MaterialComponentsCollectionCells", targets: ["MaterialComponentsCollectionCells"]),
        .library(name: "MaterialComponentsCollectionLayoutAttributes", targets: ["MaterialComponentsCollectionLayoutAttributes"]),
        .library(name: "MaterialComponentsCollections", targets: ["MaterialComponentsCollections"]),
        .library(name: "MaterialComponentsDialogs", targets: ["MaterialComponentsDialogs"]),
        .library(name: "MaterialComponentsFeatureHighlight", targets: ["MaterialComponentsFeatureHighlight"]),
        .library(name: "MaterialComponentsFlexibleHeader", targets: ["MaterialComponentsFlexibleHeader"]),
        .library(name: "MaterialComponentsHeaderStackView", targets: ["MaterialComponentsHeaderStackView"]),
        .library(name: "MaterialComponentsInk", targets: ["MaterialComponentsInk"]),
        .library(name: "MaterialComponentsMaskedTransition", targets: ["MaterialComponentsMaskedTransition"]),
        .library(name: "MaterialComponentsNavigationBar", targets: ["MaterialComponentsNavigationBar"]),
        .library(name: "MaterialComponentsOverlayWindow", targets: ["MaterialComponentsOverlayWindow"]),
        .library(name: "MaterialComponentsPageControl", targets: ["MaterialComponentsPageControl"]),
        .library(name: "MaterialComponentsPalettes", targets: ["MaterialComponentsPalettes"]),
        .library(name: "MaterialComponentsProgressView", targets: ["MaterialComponentsProgressView"]),
        .library(name: "MaterialComponentsShadowElevations", targets: ["MaterialComponentsShadowElevations"]),
        .library(name: "MaterialComponentsShadowLayer", targets: ["MaterialComponentsShadowLayer"]),
        .library(name: "MaterialComponentsSlider", targets: ["MaterialComponentsSlider"]),
        .library(name: "MaterialComponentsSnackbar", targets: ["MaterialComponentsSnackbar"]),
        .library(name: "MaterialComponentsTabs", targets: ["MaterialComponentsTabs"]),
        .library(name: "MaterialComponentsTextFields", targets: ["MaterialComponentsTextFields"]),
        .library(name: "MaterialComponentsThemes", targets: ["MaterialComponentsThemes"])
    ],
    targets: [
        .target(name: "MaterialComponentsActivityIndicator", path: "components/ActivityIndicator", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsAnimationTiming", path: "components/AnimationTiming", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsAppBar", path: "components/AppBar", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsBottomAppBar", path: "components/BottomAppBar", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsBottomSheet", path: "components/BottomSheet", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsButtonBar", path: "components/ButtonBar", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsButtons", path: "components/Buttons", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsCollectionCells", path: "components/CollectionCells", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsCollectionLayoutAttributes", path: "components/CollectionLayoutAttributes", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsCollections", path: "components/Collections", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsDialogs", path: "components/Dialogs", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsFeatureHighlight", path: "components/FeatureHighlight", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsFlexibleHeader", path: "components/FlexibleHeader", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsHeaderStackView", path: "components/HeaderStackView", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsInk", path: "components/Ink", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsMaskedTransition", path: "components/MaskedTransition", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsNavigationBar", path: "components/NavigationBar", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsOverlayWindow", path: "components/OverlayWindow", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsPageControl", path: "components/PageControl", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsPalettes", path: "components/Palettes", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsProgressView", path: "components/ProgressView", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsShadowElevations", path: "components/ShadowElevations", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsShadowLayer", path: "components/ShadowLayer", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsSlider", path: "components/Slider", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsSnackbar", path: "components/Snackbar", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsTabs", path: "components/Tabs", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsTextFields", path: "components/TextFields", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")]),
        .target(name: "MaterialComponentsThemes", path: "components/Themes", publicHeadersPath: "src", cSettings: [.headerSearchPath("src")])
    ]
)
